GET http://localhost:5001/employee/appA

###
GET http://localhost:5001/employee/appB

###
GET http://localhost:5001/employee/1

###
GET http://localhost:5001/employee/appB/1


###
POST http://localhost:5001/employee 
content-Type: application/json

{   
    "name":"ishanka",
    "email":"ish@gmail.com",
    "mobile": 44444
}

###
PUT  http://localhost:5001/employee/1
content-Type: application/json

{
    "name":"ishanka",
    "email":"ish@gmail.com",
    "mobile": 54
}

###
PUT  http://localhost:5001/employee/1
content-Type: application/json

{
    "address":"kaduwela"
}

###
DELETE  http://localhost:5001/employee/1